<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <Version>1.1.0</Version>
    <PackageVersion>1.1.0</PackageVersion>
    <Authors>Niladri Prasad Padhy</Authors>
    <Company>Nuvyntra Labs</Company>
    <Copyright>Copyright (c) Niladri Prasad Padhy</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://nuvyntralabs.github.io/toolkits/nuvloc/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/nuvyntralabs/NuvLoc</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>dotnet-maui;maui;wpf;winui;avalonia;uno;i18n;localization;cli;dotnet-tool;nuvloc</PackageTags>
  </PropertyGroup>
</Project>
